### ISSUE TITLE
关于网页版

### ISSUE THREAD

**Issue by qaqland** [RanKKI/LawRefBook#10]
有没有网页版相关计划，方便用电脑 ~摸鱼~ 学习

**Comment by RanKKI** [comment]
网页版可以看下 https://flk.npc.gov.cn/， 这个是人大办公室维护的。

**Comment by ghost** [comment]
可以用 Gitbook 自建一个小的
https://lawbook.cf

**Comment by RanKKI** [comment]
> 可以用 Gitbook 自建一个小的 https://lawbook.cf

可以的， 但注意下 License 吧， 其中那份攻略是出自 996.law

**Comment by qaqland** [comment]
> 可以用 Gitbook 自建一个小的 https://lawbook.cf

就看你这个啦！！

**Comment by qaqland** [comment]
> 网页版可以看下 [https://flk.npc.gov.cn/，](https://flk.npc.gov.cn/%EF%BC%8C) 这个是人大办公室维护的。

官方的网站看起来很严肃，没有摸鱼的感觉 XD
