### ISSUE TITLE
建议将司法解释放入各部门法之下

### ISSUE THREAD

**Issue by rickylsr** [RanKKI/LawRefBook#14]
HI，开发者

各个部门法司法解释在法律实践中应用非常广泛，对法条的应用具有权威指导意义。因此建议在完善各部门法法条的同时，也要考虑对应的司法解释，因此建议优化一下workflow，将司法解释也作为各个部门法的一部分收集完善

**Comment by RanKKI** [comment]
确实， 司法解释很重要。
目前是有几部解释，准备周末把常规法律完善之后整司法解释。
但因为解释很多， 我还没想好怎么处理内容太多之后的快速检索。

**Comment by RanKKI** [comment]
哦对， 关于放各个部门下面。 
我在信息界面加了个 “相关法”，会把相关的法律，规定，司法解释放进去，
