### ISSUE TITLE
全文搜索功能在 M1 macOS Monterey 上无法搜索

### ISSUE THREAD

**Issue by stardiviner** [RanKKI/LawRefBook#15]
操作系统: `M1 Mac Mini, macOS Monterey 12.3`

![image](https://user-images.githubusercontent.com/378699/158941827-a05361c2-9005-4f7a-b30e-a705ee35591f.png)

**Comment by RanKKI** [comment]
目前只支持目录搜索和某部法律内的全文搜索，
可能是这个全文有点歧义。。
search hint 已经改了。

**Comment by stardiviner** [comment]
以后会加这个功能么？感觉全文 full context 搜索还是很有必要的。

**Comment by RanKKI** [comment]
iOS 上正在提审的版本加上了 Spotlight 的索引， 理论上能代替全部法律的全文搜索。
软件内加不加... 在看看吧， 没想好怎么做。

**Comment by stardiviner** [comment]
嗯嗯嗯，我直接下载法律文本，然后用文本搜索工具代替吧。感谢你的作品。
