### ISSUE TITLE
深色模式下显示问题

### ISSUE THREAD

**Issue by TAKETODAY** [RanKKI/LawRefBook#24]
深色模式下显示如下

![IMG_0208](https://user-images.githubusercontent.com/29427694/159164141-3584d9a6-32b1-4637-8382-8ed937a00570.PNG)

**Comment by RanKKI** [comment]
已修复。

是我没做 dark mode 的适配... 
正在提审 0.4.1

**Comment by TAKETODAY** [comment]
谢谢 👍
