### ISSUE TITLE
夜间模式下条纹都会变成白块，无法阅读

### ISSUE THREAD

**Issue by KElee01** [RanKKI/LawRefBook#29]
如图
![image](https://user-images.githubusercontent.com/54350573/159245472-a5703833-c5bb-474c-b3d2-bdb25d334414.png)
附加一张同界面关闭夜间模式的截图
![image](https://user-images.githubusercontent.com/54350573/159245657-a48a200e-1ccf-43fb-82ae-9ecdafb115f2.png)

**Comment by RanKKI** [comment]
Duplicate of #24 
已经修复了，苹果审核中

**Comment by KElee01** [comment]
@RanKKI 不好意思没看 closed issue。不过也建议还是不要在更新发布之前关闭issue，不然总有人重新提这个问题。
还是辛苦开发者了！APP 很棒！

**Comment by RanKKI** [comment]
确实。

**Comment by RanKKI** [comment]
已上线。
