### ISSUE TITLE
建议录入《劳动法》和《劳动合同法》

### ISSUE THREAD

**Issue by huangbqsky** [RanKKI/LawRefBook#40]
《劳动法》和《劳动合同法》是打工人们最需要最重要的法律之一，尤其是在大裁员背景下，也建议加入一些案例以及对应适用条文和司法解释

**Comment by RanKKI** [comment]
嗯，确实， 但已经有了
在社会法分类下面，有劳动和劳动合同法， 
甚至还有 
 - 国家机关、事业单位贯彻《国务院关于职工工作时间的规定》的实施办法
 - 劳动仲裁和劳动诉讼的攻略
