### ISSUE TITLE
地方性法规

### ISSUE THREAD

**Issue by RanKKI** [RanKKI/LawRefBook#5]

**Comment by DiamonWoo** [comment]
建议排除地方性法规，否则后续更新压力太大，不完整会使项目价值打折扣。

**Comment by RanKKI** [comment]
> 建议排除地方性法规，否则后续更新压力太大，不完整会使项目价值打折扣。

更新速度是的问题。
但如果没有地方性法规， 比如我搜噪声污染防治，我更想搜的其实是当地的条例。毕竟条例中规定了具体的装修时间段之类的事情。

**Comment by DiamonWoo** [comment]
有用最重要，那就换个思路。
先收录自己本省的法规，做个榜样；然后写教程，指导他人发布其他省份的版本。
法律，用的人越多越有用。
