### ISSUE TITLE
民诉法解释是老版本的，没同步成新版本 (⁎⁍̴̛ᴗ⁍̴̛⁎)‼

### ISSUE THREAD

**Issue by ryu2gaku** [RanKKI/LawRefBook#51]
开发者你好，你开发的这个软件特别好用 (⁎⁍̴̛ᴗ⁍̴̛⁎)‼
通报一下内容谬误
最高人民法院关于适用《中华人民共
和国民事诉讼法》 的解释，这个法条是老版本的，22年有新版本的

**Comment by RanKKI** [comment]
国家法律法规数据库竟然没有没有更新2022年的......
哎，心累。。。。

**Comment by RanKKI** [comment]
已跟着 0.9.1 发布～
感谢反馈
