### ISSUE TITLE
可考虑添加 《关于职工全年月平均工作时间和工资折算问题的通知》

### ISSUE THREAD

**Issue by Vsnoy** [RanKKI/LawRefBook#57]
http://www.mohrss.gov.cn/xxgk2020/fdzdgknr/zcfg/gfxwj/ldgx/202011/t20201102_394696.html

这个对于打工人来说，感觉还是挺有用的。
尤其是离职当月有节假日，然后单位结算工资扯皮的时候。

**Comment by RanKKI** [comment]
好～
