### ISSUE TITLE
可否有Intel的macOS版本？

### ISSUE THREAD

**Issue by DrClairvoyant** [RanKKI/LawRefBook#60]
本人没有M1芯片的Mac，之前在iOS App Store看到这个软件真的很好用，能不能顺便出一个适配Intel芯片的macOS版本？我看整个app都是用swift语言开发应该会比较容易搬过来吧？

**Comment by asakimio** [comment]
其实就没有Mac版吧，M1装的是iPad用的版本。桌面端用网页就行了
