### ISSUE TITLE
有没有接入ChatGPT的打算呢

### ISSUE THREAD

**Issue by WSL0809** [RanKKI/LawRefBook#62]
如题，如果需要的话我愿意帮忙，不过水平有限。

**Comment by y377** [comment]
> 如题，如果需要的话我愿意帮忙，不过水平有限。
@WSL0809 
如果你愿意，可以帮我，我有这个打算，请先看[demo](https://fa.wiki.xin/)版本，正愁没有人加入呢。
ps: 由于没有开发经验，学开发还不到一年，属于半路出家，由于是用本地计算机开发，还搞丢了一部分源代码，网页端暂时比较丑陋，但是已经进入了重新设计阶段，期待的功能逻辑正在逐一攻克，如果愿意，请通过[demo](https://fa.wiki.xin/)首页底部邮箱发一封邮件给我，我留给你联系方式！
