### ISSUE TITLE
搜索框没法用

### ISSUE THREAD

**Issue by Chaiyahang** [RanKKI/LawRefBook#9]
搜索框🔍点击没反应，我是使用Mac打开的（芯片 Apple M1 Pro）

**Comment by RanKKI** [comment]
当打开过一个 sheet，搜索就能用了。 可能是 SwiftUI 的bug，我有时间查查

**Comment by Chaiyahang** [comment]
> 当打开过一个 sheet，搜索就能用了。 可能是 SwiftUI 的bug，我有时间查查

好嘞，感谢作者大大
